soc: hisilicon: hisi_hbmdev: Fix compile error
hulk inclusion
category: feature
bugzilla: https://gitee.com/openeuler/kernel/issues/I90I68
CVE: NA

---------------------------

Fix the compile error when compiling hisi_hbmdev.ko and COMPILE_TEST
is open. The reason is that cpu_l2c_id is not exported in ARCH x86_64.

ERROR: modpost: "cpu_l2c_id" [drivers/soc/hisilicon/hisi_hbmdev.ko] undefined!
make[2]: *** [scripts/Makefile.modpost:145: Module.symvers] Error 1
make[1]: *** [/home/jenkins/agent/workspace/multiarch/openeuler/x86-64/kernel/openeuler/kernel/Makefile:1874: modpost] Error 2
make: *** [Makefile:234: __sub-make] Error 2

Signed-off-by: Zhang Zekun <zhangzekun11@huawei.com>