alinux: psi: using cpuacct_cgrp_id under CONFIG_CGROUP_CPUACCT
maillist inclusion
category: feature
bugzilla: https://gitee.com/openeuler/kernel/issues/I8QUNW

Reference: https://github.com/alibaba/cloud-kernel/commit/1bd8a72b11818535b18984227ec1d707e6605e71

----------------------------------------------

This is to fix the build error if CONFIG_CGROUP_CPUACCT is not enabled.
  kernel/sched/psi.c: In function 'iterate_groups':
  kernel/sched/psi.c:732:31: error: 'cpuacct_cgrp_id' undeclared (first use in this function); did you mean 'cpuacct_charge'?

Reported-by: kbuild test robot <lkp@intel.com>
Fixes: 1f49a7385032 ("alinux: psi: Support PSI under cgroup v1")
Signed-off-by: Joseph Qi <joseph.qi@linux.alibaba.com>
Reviewed-by: Xunlei Pang <xlpang@linux.alibaba.com>
Conflict:
	kernel/sched/psi.c
Signed-off-by: Lu Jialin <lujialin4@huawei.com>