kasan: fix the compilation error for memcpy_mcs()
hulk inclusion
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/I8MWHA
CVE: NA

--------------------------------

Fix the compilation error when CONFIG_KASAN=y:
  error: implicit declaration of function ‘check_memory_region’;

Fixes: 23ca830ebbef ("arm64: introduce copy_mc_to_kernel() implementation")
Signed-off-by: Tong Tiangen <tongtiangen@huawei.com>