arm64: Fix compilation error with ILP32 support
hulk inclusion
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/I8S6IA

-------------------------------------------------

This patch fix the following compilation errors with ILP32 support
using openeuler_defcofig.

When ILP32 support is enabled, compilation on ARM64 would complain
about an undeclared __NR_compat_syscalls, since commit b16c8a680a2b
("arm64: ilp32: introduce syscall table for ILP32") changes the config
that __NR_compat_syscalls depends on but commit dbece8b041f3 ("arm64:
rename COMPAT to AARCH32_EL0") ignores it for __NR_compat_syscalls.
Modify the config for SECCOMP_ARCH_COMPAT_NR accordingly.

And commit dbece8b041f3 ("arm64: rename COMPAT to AARCH32_EL0") ignores
ARM64_ERRATU_1742098 which only depends on AARCH32_EL0 but not ARM64_ILP32.

compat_elf_gregset_t is used in elfcore-compat.h but only defined in
binfmt_ilp32.c which depends on ARM64_ILP32, so move it to elf.h.

Commit 7de3ab4c3dd9 ("arm64: introduce binfmt_elf32.c") rename COMPAT to
AARCH32_EL0 for compat_elf_check_arch(), but compat_binfmt_elf.c also
uses it with ILP32 support, so changes it back. And make
EF_ARM_EABI_MASK and compat_elf_check_arch() function declaration to be
common for ARM64_ILP32 and AARCH32_EL0.

	./arch/arm64/include/asm/seccomp.h:57:33: error: ‘__NR_compat_syscalls’ undeclared here (not in a function); did you mean ‘in_compat_syscall’?
	   57 | # define SECCOMP_ARCH_COMPAT_NR __NR_compat_syscalls

	./arch/arm64/kernel/cpufeature.c:2200:17: error: ‘a32_elf_hwcap2’ undeclared (first use in this function); did you mean ‘elf_hwcap’?
	 2200 |                 a32_elf_hwcap2 &= ~COMPAT_HWCAP2_AES;
	      |                 ^~~~~~~~~~~~~~
	      |                 elf_hwcap

	./include/linux/elfcore-compat.h:62:9: error: unknown type name ‘compat_elf_gregset_t’
	   62 |         compat_elf_gregset_t            pr_reg;
	      |         ^~~~~~~~~~~~~~~~~~~~

	./fs/compat_binfmt_elf.c:66:25: error: implicit declaration of function ‘compat_elf_check_arch’; did you mean ‘elf_check_arch’? [-Werror=implicit-function-declaration]
	   66 | #define elf_check_arch  compat_elf_check_arch
	      |                         ^~~~~~~~~~~~~~~~~~~~~

Fixes: dbece8b041f3 ("arm64: rename COMPAT to AARCH32_EL0")
Fixes: 7de3ab4c3dd9 ("arm64: introduce binfmt_elf32.c")
Signed-off-by: Jinjie Ruan <ruanjinjie@huawei.com>