memig: fix compile error when CONFIG_NUMA is turned off
euleros inclusion
category: feature
feature: memig
bugzilla: https://gitee.com/openeuler/kernel/issues/I7RO5Q
Reference: https://gitee.com/openeuler/kernel/commit/74706f34e144e1bf95914d2e36eb29d40f1d8e14

-------------------------------------------------

fix compile error when CONFIG_NUMA is turned off on Raspberry platform.

compile info:
mm/vmscan.c: In function ‘get_page_from_vaddr’:
mm/vmscan.c:4350:40: error: implicit declaration of function ‘vma_migratable’;
did you mean ‘rq_mergeable’? [-Werror=implicit-function-declaration]

This patch solves the problem of compilation errors
introduced by memig into the interface in the vmscan.c
file. Delete dependency on NUMA for CONFIG_MEMIG_SWAP,
and use vma->vm_flags & VM_LOCKED for judgement.

Signed-off-by: liubo <liubo254@huawei.com>
Reviewed-by: Jing Xiangfeng <jingxiangfeng@huawei.com>
Signed-off-by: Zheng Zengkai <zhengzengkai@huawei.com>