livepatch: Fix compile error when CONFIG_LIVEPATCH_WO_FTRACE disabled
hulk inclusion
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/I60NAZ
CVE: NA

--------------------------------

When disable CONFIG_LIVEPATCH_WO_FTRACE, compiler report following error:
  kernel/livepatch/core.c: In function ‘check_address_conflict’:
  kernel/livepatch/core.c:1214:18: error: ‘KLP_MAX_REPLACE_SIZE’
  undeclared (first use in this function)
   1214 |    end = start + KLP_MAX_REPLACE_SIZE - 1;
        |                  ^~~~~~~~~~~~~~~~~~~~
  kernel/livepatch/core.c:1214:18: note: each undeclared identifier is
  reported only once for each function it appears in
  At top level:
  kernel/livepatch/core.c:1195:12: warning: ‘check_address_conflict’
  defined but not used [-Wunused-function]
   1195 | static int check_address_conflict(struct klp_patch *patch)
        |            ^~~~~~~~~~~~~~~~~~~~~~

Fixes: af56c7290f29 ("[Huawei] livepatch/x86: Avoid conflict with static {call,key}")
Fixes: aba04b9defb0 ("[Huawei] livepatch/core: Restrict minimum size of function that can be patched")
Signed-off-by: Zheng Yejian <zhengyejian1@huawei.com>