tcp: Add a stub for sk_defer_free_flush()
mainline inclusion
from mainline-v5.16
commit 48cec899e357cfb92d022a9c0df6bbe72a7f6951
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/I6J2YZ
CVE: NA

----------------------------------------

When compiling the kernel with CONFIG_INET disabled, the
sk_defer_free_flush() should be defined as a nop.

This resolves the following compilation error:
  ld: net/core/sock.o: in function `sk_defer_free_flush':
  ./include/net/tcp.h:1378: undefined reference to `__sk_defer_free_flush'

Fixes: 79074a72d335 ("net: Flush deferred skb free on socket destroy")
Reported-by: kernel test robot <lkp@intel.com>
Reviewed-by: Tariq Toukan <tariqt@nvidia.com>
Signed-off-by: Gal Pressman <gal@nvidia.com>
Reviewed-by: Eric Dumazet <edumazet@google.com>
Link: https://lore.kernel.org/r/20220120123440.9088-1-gal@nvidia.com
Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: leoliuoc <leoliu-oc@zhaoxin.com>